# Generated by Django 4.1 on 2022-11-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_alter_voting_postproc_alter_voting_tally'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voting',
            name='model',
            field=models.CharField(choices=[('IDENTITY', 'Identity'), ('DHONDT', "D'Hondt")], default='IDENTITY', max_length=8),
        ),
    ]
