# Generated by Django 4.1 on 2023-11-13 20:49

from django.db import migrations, models
import django.db.models.deletion
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_voting_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cattegory',
            field=models.CharField(choices=[('YES/NO', 'yes/no'), ('OPTIONS', 'options')], default='', max_length=8),
        ),
        migrations.CreateModel(
            name='QuestionYesNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='', max_length=8, verbose_name=voting.models.Question)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_yes_no', to='voting.question')),
            ],
        ),
    ]
