# Generated by Django 4.1 on 2023-11-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_question_cattegory_questionyesno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionyesno',
            name='option',
        ),
        migrations.RemoveField(
            model_name='questionyesno',
            name='question',
        ),
        migrations.AddField(
            model_name='questionyesno',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
