# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from django.contrib.staticfiles.testing import StaticLiveServerTestCase

class TestGoodLogin(StaticLiveServerTestCase):
  def setUp(self):
    #Opciones de Chrome
    options = webdriver.ChromeOptions()
    options.headless = True
    self.driver = webdriver.Chrome(options=options)
  
  def tearDown(self):
    super().tearDown()
    self.driver.quit()
  
  def test_goodLogin(self):
    self.driver.get("http://0.0.0.0:8080/admin/login/?next=/admin/")
    self.driver.set_window_size(1038, 1016)
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("admin")
    self.driver.find_element(By.CSS_SELECTOR, ".submit-row > input").click()

    self.assertTrue(len(self.driver.find_elements(By.ID, 'user-tools'))==1)
  
