# Generated by Selenium IDE
import pytest
import time
import json

from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from base import mods
from base.tests import BaseTestCase

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestNewVoting(StaticLiveServerTestCase):
    def setUp(self):
        options = webdriver.ChromeOptions()
        options.headless = False
        self.driver = webdriver.Chrome(options=options)

        super().setUp()

    def tearDown(self):
        super().tearDown()
        self.driver.quit()

  
    def test_newVoting(self):
        self.driver.get("http://127.0.0.1:8000/")
        self.driver.set_window_size(1038, 1016)
        self.driver.find_element(By.NAME, "username").click()
        self.driver.find_element(By.NAME, "username").send_keys("admin")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("admin")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
        self.driver.find_element(By.ID, "votacionDropdown").click()
        self.driver.find_element(By.LINK_TEXT, "Nueva Votación").click()
        self.driver.find_element(By.ID, "id_name").click()
        self.driver.find_element(By.ID, "id_name").send_keys("Votación de ejemplo")
        self.driver.find_element(By.ID, "id_desc").click()
        self.driver.find_element(By.ID, "id_desc").send_keys("descripción de ejemplo")
        dropdown = self.driver.find_element(By.ID, "id_question")
        dropdown.find_element(By.XPATH, "//option[. = '¿Es esto una votación correcta?']").click()
        element = self.driver.find_element(By.ID, "id_question")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.ID, "id_question")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
        element = self.driver.find_element(By.ID, "id_question")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        dropdown = self.driver.find_element(By.ID, "id_auths")
        dropdown.find_element(By.XPATH, "//option[. = 'http://localhost:8000']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".mt-6").click()

        self.assertTrue(self.driver.current_url == "http://127.0.0.1:8000/voting/allVotings/")
    
    def test_allVoting(self):
        self.driver.get("http://127.0.0.1:8000/")
        self.driver.set_window_size(1265, 1376)
        self.driver.find_element(By.NAME, "username").click()
        self.driver.find_element(By.NAME, "username").send_keys("admin")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("admin")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
        self.driver.find_element(By.ID, "votacionDropdown").click()
        self.driver.find_element(By.LINK_TEXT, "Votaciones").click()

    def test_newauth(self):
        self.driver.get("http://127.0.0.1:8000/")
        self.driver.set_window_size(1850, 1016)
        self.driver.find_element(By.NAME, "username").click()
        self.driver.find_element(By.NAME, "username").send_keys("admin")
        self.driver.find_element(By.NAME, "password").click()
        self.driver.find_element(By.NAME, "password").send_keys("admin")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
        self.driver.find_element(By.ID, "votacionDropdown").click()
        self.driver.find_element(By.LINK_TEXT, "Nuevo auth").click()
        self.driver.find_element(By.ID, "id_name").click()
        self.driver.find_element(By.ID, "id_name").send_keys("Nuevo_auth")
        self.driver.find_element(By.ID, "id_url").click()
        self.driver.find_element(By.ID, "id_url").send_keys("http://localhost:8000")
        self.driver.find_element(By.CSS_SELECTOR, ".mt-6").click()

